### PR TITLE
Material2

### PR DESCRIPTION
**Pull request by 0-kaladin**
Addresses Issue #592 
all credit to @Lozone

### CODE REVIEW

**Comment by xd1936** [comment]
This is fantastic. Great work!

**Comment by dschuermann** [comment]
@0-kaladin Have you tested these changes?

**Comment by 0-kaladin** [comment]
Yes the commits on Mar 21 fixed the issues people were seeing who were NOT on Lollipop.  You have to define a v21 style which is in the Mar 21 commits.

**Comment by dschuermann** [comment]
@Lozone @0-kaladin Are the source files of the icon available? svg, ai or somthing similar?

**Comment by Lozone** [comment]
The icons within Adaway are found here.
http://shreyasachar.com/AndroidAssetStudio/index.html

The app launcher icon itself was made by me using the Adaway dove from the icon.xcf found in the Resources folder.

**Comment by dschuermann** [comment]
@Lozone Can you please include your modified icon.xcf to allow future modifications

**Comment by adrientetar** [comment]
ping @Lozone

**Comment by 0-kaladin** [comment]
@dschuermann please check latest updates.

**Comment by dschuermann** [comment]
Works great on Lollipop. I am currently unable to test it on Android < 5.0 due to a business trip. Can someone confirm that this is also working on 4.1 to 4.4?

**Comment by 0-kaladin** [comment]
i've confirmed 4.4 as well.  the xda thread with users, no one has complained about it not working.

**Comment by dschuermann** [comment]
Awesome work. I should release a New Version.. Are there any blockers @0-kaladin ?

**Comment by 0-kaladin** [comment]
@dschuermann Nope.  No known blockers.  The largest change would be the support of JB or > only for a next version.  The poll on XDA for how many that would effect was at 4%.  From about 2800.  
anyone on older can safely stay on 2.9.2 its not like new features were added.  just support for 5.x with PIE, updates to third party stuff, material design,  nothing core to functionality.  So I think a safe bump.

**Comment by dschuermann** [comment]
@0-kaladin I just build AdAway with the newest Android NDK 10d and tested everything. tcpdump and the webserver are not working for me. I am running a cyanogenmod nightly. But the last version from F-Droid is also not working for me :/
So I just re-added the oom killer prevention for the webserver in https://github.com/sufficiently-secure/ad-away/commit/3872b2232ffb9f113ddecb9298b142c481d3a3e1 and tagged a new version as I can not afford to put more time in it. Should appear on F-Droid soon.

**Comment by 0-kaladin** [comment]
@dschuermann just for clarity, after you added the oom killer did it work for you? I have a nexus5 i could probably get cyan on to test.  could be an selinux thing if they are enforcing.

**Comment by dschuermann** [comment]
The compilation worked and the code is not much different to what we have had in past versions of blank_webserver, so I assume it works in general.
On my cyanogenmod nightly neither the webserver nor the tcpdump gets started properly so I assume it is a specific problem on my device/Android distribution. SeLinux is most probably the cause of this problem.

**Comment by 0-kaladin** [comment]
Well I can't duplicate.  Here is what I did.  Flashed a nexus5 with lastest google 5.1 (to get bootloader, radio, etc.)  then using fastboot flashed twrp-2.8.6.1-hammerhead.img
then in twrp flashed: cm-12-20150409-NIGHTLY-hammerhead.zip, and then BETA-SuperSU-v2.48.zip.

Installed my build of adaway from your 3.0 tag.  I can start webserver and tcpdump.  I browsed web pages and saw logs in tcpdump so i know its working.  I told the webserver to run at boot and rebooted.  after reboot webserver was still running confirmed via adb shell:root@hammerhead:/ # netstat -vulpn
Proto Recv-Q Send-Q Local Address          Foreign Address        State
 tcp       0      0 127.0.0.1:5037         0.0.0.0:*              LISTEN
 tcp       0      0 127.0.0.1:80           0.0.0.0:*              LISTEN
 tcp       0      0 127.0.0.1:443          0.0.0.0:*              LISTEN

I really want your own app to work for you but I see no issues.  Only suggestion is to maybe ensure you try that beta supersu.  I thought it really just fixed things for 5.1 and that nightly is 5.0.2 based but who knows.

**Comment by dschuermann** [comment]
> I really want your own app to work for you but I see no issues. Only suggestion is to maybe ensure you try that beta supersu. I thought it really just fixed things for 5.1 and that nightly is 5.0.2 based but who knows.
@dschuermann in case you didn't see.

No worries :) As long as it works for the users it's fine. I am currently mainly using open source software without ads.

**Pull request merged**
